SELECT ADD_TO_CART_QUANTITY,
        ITEM_NAME,
        ITEM_VIEW_AT AS ITEM_VIEW_TS,
        PRICE_PER_UNIT,
        REMOVE_FROM_CART_QUANTITY,
        ADD_TO_CART_QUANTITY-REMOVE_FROM_CART_QUANTITY AS STAY_IN_CART_QUANTITY,
        SESSION_ID,
        _FIVETRAN_DELETED,
        _FIVETRAN_ID,
        _FIVETRAN_SYNCED AS _FIVETRAN_SYNCED_TS        
FROM {{ source('snowflake_web', 'item_views') }}