version: 2

sources:
  - name: snowflake_web
    database: LOAD
    schema: SNOWFLAKE_DB_WEB_SCHEMA
    tables:
      - name: item_views
        freshness:
          warn_after:
            count: 1
            period: day
          error_after:
            count: 2
            period: day
        loaded_at_field: _fivetran_synced
      - name: orders
        freshness:
          warn_after:
            count: 1
            period: day
          error_after:
            count: 2
            period: day
        loaded_at_field: _fivetran_synced
      - name: page_views
        freshness:
          warn_after:
            count: 1
            period: day
          error_after:
            count: 2
            period: day
        loaded_at_field: _fivetran_synced
      - name: sessions
        freshness:
          warn_after:
            count: 1
            period: day
          error_after:
            count: 2
            period: day
        loaded_at_field: _fivetran_synced
  - name: google_drive
    database: LOAD
    schema: GOOGLE_DRIVE
    tables:
      - name: expenses
      - name: hr_joins
      - name: hr_quist
      - name: returns
